---
run_cli_url:
#run_bootstrap_url: https://raw.githubusercontent.com/rajnish-jauhari/skupper/refs/heads/non-kube/cmd/bootstrap/bootstrap.sh
run_bootstrap_url: https://raw.githubusercontent.com/skupperproject/skupper/refs/heads/main/cmd/bootstrap/bootstrap.sh