---
run_cli_url: https://github.com/skupperproject/skupper/releases/download/2.0.0/skupper-cli-2.0.0-linux-s390x.tgz
run_bootstrap_url: https://raw.githubusercontent.com/rajnish-jauhari/skupper/refs/heads/non-kube/cmd/bootstrap/bootstrap.sh
