- name: Running the frontend application
  community.general.docker_container:
    name: frontend
    recreate: true
    auto_remove: true
    published_ports:
      - "127.0.0.1:7070:8080"
    image: quay.io/rhn-support-rjauhari/hello-world-frontend
    command:
      - "--backend=http://host.containers.internal:8080"

- name: Running the backend application
  community.general.docker_container:
    name: backend
    recreate: true
    auto_remove: true
    published_ports:
      - "127.0.0.1:9090:8080"
    image: quay.io/rhn-support-rjauhari/hello-world-backend
